os: osx
osx_image: xcode11.1
language: swift
install:
  - |
    brew install create-dmg
    security create-keychain -p travis build.keychain
    security default-keychain -s build.keychain
    security unlock-keychain -p travis build.keychain
    echo $CERTIFICATE_OSX_P12 | base64 --decode > certificate.p12
    security import certificate.p12 -k build.keychain -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign
    security set-key-partition-list -S apple-tool:,apple: -s -k travis build.keychain

script:
    - xcodebuild clean build -project ReaderTranslator.xcodeproj -scheme 'ReaderTranslatorMac' -sdk macosx -configuration Debug -derivedDataPath ./build | xcpretty -c
    - cp -R build/Build/Products/Debug/ReaderTranslatorMac.app .
    - create-dmg --volname "Application Installer" --hide-extension "Application.app" --app-drop-link 600 185 "ReaderTranslatorMac.dmg" "ReaderTranslatorMac.app/"
    - find ReaderTranslatorMac *.dmg
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: false
  api_key: $GITHUB_TOKEN
  file:
    - ReaderTranslatorMac
    - ReaderTranslatorMac.dmg
  on:
    tags: true
    branch: master
    repo: filimo/ReaderTranslator
branches:
  only:
  - master
  - /^\d+\.\d+\.\d+.*$/
